CC = g++
FILES1 = AVLTree.cpp 
FILES2 = AVLTree.h
FILES3 = main.cpp 
OUT_EXE = avlfreq

build: $(FILES)
	$(CC) -o $(OUT_EXE) $(FILES1) $(FILES2) $(FILES3)

clean:
	rm -f *.o core

rebuild: clean build

